import categoriesData from '@/data/ios-symbols/categories.json';
import languagesData from '@/data/ios-symbols/languages.json';
import manifestData from '@/data/ios-symbols/manifest.json';

import type { Metadata } from 'next';

import { SymbolBrowser } from './_components/symbol-browser';
import type { CategoryDef, Languages, SymbolEntry } from './_lib/types';

// The committed JSON is generated by `symbols:meta` (see packages/icons/scripts/build-manifest.mjs).
// TypeScript widens the imported literals (e.g. `facets: string[]`), so we assert the
// generator's contract here at the boundary rather than re-derive anything at runtime.
const symbols = manifestData as SymbolEntry[];
const categories = categoriesData as CategoryDef[];
const languages = languagesData as Languages;

export const metadata: Metadata = {
    title: 'SF Symbols',
    description: 'Browse, search, filter, and copy every SF Symbol shipped in packages/icons.',
};

export default function IosSymbolsPage() {
    return (
        <div className="flex flex-col">
            <div className="flex flex-col gap-1 px-4 pt-6 pb-2 sm:px-6">
                <h1 className="text-2xl font-semibold tracking-tight">SF Symbols</h1>
                <p className="text-muted-foreground text-sm">
                    Search, filter, and copy any of the {symbols.length.toLocaleString()} SF Symbols. Pick a copy format, then click a
                    symbol.
                </p>
            </div>
            <SymbolBrowser symbols={symbols} categories={categories} languages={languages} />
        </div>
    );
}
